### ISSUE TITLE
Two ROUGE lib

### ISSUE THREAD

**Issue by fgksgf** [Tbabm/PRSummarizer#1]
Hello, it seems you used two rouge lib: `pyrouge` and `rouge` (or `myrouge`), which is confused for me. Could you help me understand that ? Why not just use one ?

Thank you.

**Comment by Tbabm** [comment]
`pyrouge` is a python wrapper of the official ROUGE package, so it is used for evaluation.
The RL loss used in PRSum also needs to calculate ROUGE scores, but it is slow and inconvenient to use pyrouge when training, so I use a python implementation of ROUGE, i.e., `myrouge`.  In most cases, the results calculated by `myrouge` are equal to `pyrouge`.

**Comment by fgksgf** [comment]
Thanks for your reply. It makes sense to me.

Another question: what's the difference between `myrouge` and `rouge`(https://github.com/pltrdy/rouge)? Did you make some changes based on `rouge`?

**Comment by Tbabm** [comment]
> Another question: what's the difference between `myrouge` and `rouge`(https://github.com/pltrdy/rouge)? Did you make some changes based on `rouge`?

Yes, I made some changes to make `rouge` more close to the official ROUGE package. But I forget the detail differences. Maybe you could figure it out using diff tools.

**Comment by fgksgf** [comment]
Thanks a lot !
